export const RECEIVEEMOJIS = 'RECEIVEEMOJIS'
export const RECEIVECATEGORYL1LIST = 'RECEIVECATEGORYL1LIST '
export const RECRIVEKEYWORD = "RECRIVEKEYWORD"

export const RERIVEBUY = "RERIVEBUY"
export const RERIVELOGIN = "RERIVELOGIN"